# Generated by Django 4.2 on 2023-06-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipy',
            fields=[
                ('nazwa_ekipy', models.CharField(default='', max_length=200)),
                ('sesje_ses_number', models.CharField(default='', max_length=200)),
                ('ekipy_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_punktow', models.IntegerField(default=0)),
                ('ilosc_punkow_odwiedzonych', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gry',
            fields=[
                ('nr_gry', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('nazwa_gry', models.CharField(default='', max_length=200)),
                ('czas_trwania', models.CharField(default='', max_length=200)),
                ('lokalizacja', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hosty',
            fields=[
                ('h_nick', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('sesje_ses_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Punktowi',
            fields=[
                ('p_nick', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('ses_num', models.CharField(default='', max_length=200)),
                ('sesje_ses_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zadania',
            fields=[
                ('id_zadania', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('opis_zadania', models.CharField(default='', max_length=200)),
                ('nazwa_zadania', models.CharField(default='', max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gry_nr_gry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.gry')),
            ],
        ),
        migrations.CreateModel(
            name='Sesje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_number', models.CharField(default='', max_length=200)),
                ('game_name', models.CharField(default='', max_length=200)),
                ('end_time', models.DateTimeField(verbose_name='end date')),
                ('password', models.CharField(default='', max_length=200)),
                ('gry_nr_gry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gra.gry')),
            ],
        ),
        migrations.CreateModel(
            name='Gracze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_nick', models.CharField(default='', max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('ekipy_ekipy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.ekipy')),
            ],
        ),
    ]
